-- MySQL Script generated by MySQL Workbench
-- Wed 19 Jul 2023 10:12:10 AM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema u206369201_wcs4
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema u206369201_wcs4
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `u206369201_wcs4` DEFAULT CHARACTER SET utf8 ;
USE `u206369201_wcs4` ;

-- -----------------------------------------------------
-- Table `u206369201_wcs4`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_wcs4`.`countries` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `flag` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u206369201_wcs4`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_wcs4`.`teams` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(45) NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_teams_countries_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_teams_countries`
    FOREIGN KEY (`country_id`)
    REFERENCES `u206369201_wcs4`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u206369201_wcs4`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_wcs4`.`players` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `age` VARCHAR(45) NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(45) NOT NULL,
  `country_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_players_countries1_idx` (`country_id` ASC) VISIBLE,
  INDEX `fk_players_teams1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_players_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `u206369201_wcs4`.`countries` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_players_teams1`
    FOREIGN KEY (`team_id`)
    REFERENCES `u206369201_wcs4`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `u206369201_wcs4`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `u206369201_wcs4`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `hashed_password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
